version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blog-notification-pigeon-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sc7kz5mo7bxc"
s3_prefix = "blog-notification-pigeon-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
